package ru.itmo.corp.jbevm.token;

public enum TokenType {
  // Single-character tokens.
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, ARRAY_OPEN, ARRAY_CLOSE,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, COLON, QUESTION_MARK,

  // One or two character tokens.
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  PLUS_PLUS, MINUS_MINUS,

  //Bitwise operations
  SHIFT_RIGHT, SHIFT_LEFT, LOGICAL_SHIFT_RIGHT,

  // Literals.
  IDENTIFIER, STRING, FLOAT_NUMBER, INT_NUMBER, CHAR, TRUE, FALSE, NULL,

  // Built-in data types
  BOOLEAN_TYPE, BYTE_TYPE, INT_TYPE, FLOAT_TYPE, CHAR_TYPE,
  DOUBLE_TYPE, LONG_TYPE, SHORT_TYPE, VOID_TYPE,

  // Keywords.
  BREAK, CATCH, CLASS, CONTINUE, DO, ELSE, FINAL, FOR, IF, INSTANCEOF,
  NEW, RETURN, STATIC, SUPER, THIS, THROW, THROWS, TRY, WHILE,

  EOF,
}
